# ┌───────────────────────────────────────────────┐
# │█▀▀▀▀▀▀▀▀█░░░░█░█░▀█▀░▀█▀░▀█▀░█░█░░░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀█░░░░█▀▄░░█░░░█░░░█░░░█░░░░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀█░░░░▀░▀░▀▀▀░░▀░░░▀░░░▀░░░░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀▀───────────────────────────▀▀▀▀▀▀▀▀▀█│
# ├┤ Author  : Daniel Berg <mail@roosta.sh>      ├┤
# ││ Repo    : https://github.com/roosta/dotfiles││
# ││ Site    : https://www.roosta.sh             ││
# ├┤ License : GNU General Public License v3     ├┤
# ┆└─────────────────────────────────────────────┘┆
# /usr/share/doc/kitty/kitty.conf

# General
enable_audio_bell no
shell_integration enabled
startup_session sessions/main.conf
window_padding_width 2
map kitty_mod+r load_config_file

# Font
font_family IosevkaTerm Nerd Font
bold_font auto
bold_italic_font auto
font_size 9.0
italic_font auto

# Scrollback
scrollback_lines 100000
scrollback_pager ~/.local/bin/kitty-pager
map kitty_mod+u show_scrollback
# map kitty_mod+g show_last_command_output


# Navigation
map alt+l kitten hints --type linenum
map alt+w kitten hints --type word --program -
map alt+p kitten hints --type path --program dolphin
map alt+u open_url_with_hints

# Theme
include ~/.config/srcery/srcery-terminal/kitty/srcery_kitty.conf

# Kitty-scrollback
allow_remote_control socket-only
listen_on unix:/tmp/kitty
action_alias kitty_scrollback_nvim kitten ~/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
map kitty_mod+h kitty_scrollback_nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
