[general]
default_icon = ""
# separator = "  "

[options]
remove_duplicates = true

[icons]
"Firefox" = ""
"Firefox Developer" = ""
"Firefox Media" = ""
Termite = ""
Thunderbird = ""
Chrome-dev = ""
Chrome= ""
Spotify = ""
libreoffice-calc = ""
"Gimp" = ""
Transmission = ""
com-eviware-soapui-SoapUI = ""
"Nautilus" = ""
"web.whatsapp.com" = ""
"Discord" = ""
Alacritty = ""
kitty = ""
Steam = ""
REAPER = ""
Bitwig = ""
Slack = ""
Evince = ""
Gpick = ""
Shortwave = ""
Mixer = ""
Gedit =""
Lutris ="󱎓"
Minecraft = "󰍳"
Software = "󰀻"
Flatseal = ""
Chatbox = "󱜸"
"OBS Studio"=""

[aliases.app_id]
firefox-developer-edition = "Firefox Developer"
libreoffice-calc = "Calc"
"^firefox$" = "Firefox"
"^firefox-media$" = "Firefox Media"
Google-chrome-unstable = "Chrome-dev"
Google-chrome = "Chrome"
".*(?i)transmission" = "Transmission"
"org.gnome.Nautilus" = "Nautilus"
"com\\.bitwig\\.BitwigStudio" = "Bitwig"
jetbrains-idea-ce = "IntelliJ"
thunderbird = "Thunderbird"
shortwave = "Shortwave"
pavucontrol = "Mixer"
".*(?i)lutris" = "Lutris"
".*(?i)shortwave" = "Shortwave"
".*(?i)discord" = "Discord"
"(?i)org.gnome.software" = "Software"
".*(?i)flatseal" = "Flatseal"
"xyz.chatboxapp.app" = "Chatbox"
gpick="Gpick"
spotify="Spotify"
"com.obsproject.Studio"="OBS Studio"

[aliases.class]
steam = "Steam"
"(?i)minecraft.*" = "Minecraft"
"Gimp-\\d\\.\\d\\d" = "Gimp"
"xyz.chatboxapp.app" = "Chatbox"

[aliases.instance]
"open.spotify.com" = "Spotify"
