# Monitors
$primary_monitor = DP-1
monitor = $primary_monitor,preferred,auto,2

workspace = 1, monitor:$primary_monitor, default:true, persistent:true, layout:dwindle
workspace = 2, monitor:$primary_monitor, persistent:true, layout:dwindle
workspace = 3, monitor:$primary_monitor, persistent:true
workspace = 4, monitor:$primary_monitor, persistent:true
workspace = 5, monitor:$primary_monitor, persistent:true
workspace = 6, monitor:$primary_monitor, persistent:true
workspace = 7, monitor:$primary_monitor, persistent:true
workspace = 8, monitor:$primary_monitor, persistent:true
workspace = 9, monitor:$primary_monitor, persistent:true
workspace = 10, monitor:$primary_monitor, persistent:true
