# ┌────────────────────────────────────────────────────────┐
# │█▀▀▀▀▀▀▀▀█░░░█▄█░█▀█░█▀█░▀█▀░▀█▀░█▀█░█▀▄░█▀▀░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀█░░░█░█░█░█░█░█░░█░░░█░░█░█░█▀▄░▀▀█░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀█░░░▀░▀░▀▀▀░▀░▀░▀▀▀░░▀░░▀▀▀░▀░▀░▀▀▀░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀▀────────────────────────────────────▀▀▀▀▀▀▀▀▀█│
# ├┤ Author  : Daniel Berg <mail@roosta.sh>               ├┤
# ││ Repo    : https://github.com/roosta/dotfiles         ││
# ││ Site    : https://www.roosta.sh                      ││
# ├┤ License : GNU General Public License v3              ├┤
# ┆└──────────────────────────────────────────────────────┘┆
# ┆ Mirror - Desk setup, but mirror right monitor on TV

$center_monitor  = DP-1
$left_monitor    = DP-2
$primary_monitor = DP-1
$right_monitor   = HDMI-A-1
$top_monitor     = HDMI-A-3
$tv_monitor      = HDMI-A-2

monitor = $center_monitor,3840x2160@120,0x0,2,bitdepth,10,cm,srgb,sdrbrightness,1.28,sdrsaturation,0.98,vrr,3
monitor = $left_monitor,preferred,-1920x0,2
monitor = $right_monitor,preferred,1920x0,2
monitor = $top_monitor,preferred,0x-1080,1.5
monitor = $tv_monitor,3840x2160,auto,2,bitdepth,10,cm,srgb,sdrbrightness,1.20,sdrsaturation,1.1,mirror,$right_monitor

exec = xrandr --output $primary_monitor --primary
env = PROTON_WAYLAND_MONITOR,$primary_monitor

source = ./desk_rules.conf

## Examples
# monitor = $top_monitor,preferred,1920x-1080,1
