; ┌────────────────────────────────────────────────┐
; │█▀▀▀▀▀▀▀▀█░░░█▀▄░▀█▀░▀█▀░█░█░█▀█░█░░░░█▀▀▀▀▀▀▀▀█│
; │█▀▀▀▀▀▀▀▀█░░░█▀▄░░█░░░█░░█░█░█▀█░█░░░░█▀▀▀▀▀▀▀▀█│
; │█▀▀▀▀▀▀▀▀█░░░▀░▀░▀▀▀░░▀░░▀▀▀░▀░▀░▀▀▀░░█▀▀▀▀▀▀▀▀█│
; │█▀▀▀▀▀▀▀▀▀────────────────────────────▀▀▀▀▀▀▀▀▀█│
; ├┤ Author  : Daniel Berg <mail@roosta.sh>       ├┤
; ││ Repo    : https://github.com/roosta/dotfiles ││
; ││ Site    : https://www.roosta.sh              ││
; ├┤ License : GNU General Public License v3      ├┤
; ┆└──────────────────────────────────────────────┘┆
; Configuration file for ritual-shell.
; Configured for ascii output for a datasteam used in
; ~/.config/quickshell/services/PipewireData.qml

[general]
bars = 64

[output]
method = raw
channels = stereo
data_format = ascii
ascii_max_range = 100

; vim: set ts=2 sw=2 tw=0 fdm=marker et ft=dosini :
