## Configuration file for ritual-shell.
## Configured for ascii output

[general]
bars = 64

[output]
method = raw
channels = mono
data_format = ascii
ascii_max_range = 100

; vim: set ts=2 sw=2 tw=0 fdm=marker et ft=dosini :
