# ┌───────────────────────────────────────────────┐
# │█▀▀▀▀▀▀▀▀█░░░░█▀▀░█▀█░█▄█░█▀▀░█▀▀░░░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀█░░░░█░█░█▀█░█░█░█▀▀░▀▀█░░░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀█░░░░▀▀▀░▀░▀░▀░▀░▀▀▀░▀▀▀░░░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀▀───────────────────────────▀▀▀▀▀▀▀▀▀█│
# ├┤ Author  : Daniel Berg <mail@roosta.sh>      ├┤
# ││ Repo    : https://github.com/roosta/dotfiles││
# ││ Site    : https://www.roosta.sh             ││
# ├┤ License : GNU General Public License v3     ├┤
# ┆└─────────────────────────────────────────────┘┆
# ┆ Game spesific window rules, most games don't require this
# ┆ Docs: https://wiki.hypr.land/Configuring/Uncommon-tips--tricks/#shimeji

# Nothing here at the moment
