# ┌────────────────────────────────────────────────────────┐
# │█▀▀▀▀▀▀▀▀█░░░█░█░█░█░█▀█░█▀▄░▀█▀░█▀▄░█░░░█▀▀░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀█░░░█▀█░░█░░█▀▀░█▀▄░░█░░█░█░█░░░█▀▀░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀█░░░▀░▀░░▀░░▀░░░▀░▀░▀▀▀░▀▀░░▀▀▀░▀▀▀░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀▀────────────────────────────────────▀▀▀▀▀▀▀▀▀█│
# ├┤ Author  : Daniel Berg <mail@roosta.sh>               ├┤
# ││ Repo    : https://github.com/roosta/dotfiles         ││
# ││ Site    : https://www.roosta.sh                      ││
# ├┤ License : GNU General Public License v3              ├┤
# ┆└──────────────────────────────────────────────────────┘┆
# ┆ Docs: https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/

listener {
    timeout = 900
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
