# ┌────────────────────────────────────────────────────────┐
# │█▀▀▀▀▀▀▀▀█░░░█░█░█░█░█▀█░█▀▄░▀█▀░█▀▄░█░░░█▀▀░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀█░░░█▀█░░█░░█▀▀░█▀▄░░█░░█░█░█░░░█▀▀░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀█░░░▀░▀░░▀░░▀░░░▀░▀░▀▀▀░▀▀░░▀▀▀░▀▀▀░░█▀▀▀▀▀▀▀▀█│
# │█▀▀▀▀▀▀▀▀▀────────────────────────────────────▀▀▀▀▀▀▀▀▀█│
# ├┤ Author  : Daniel Berg <mail@roosta.sh>               ├┤
# ││ Repo    : https://github.com/roosta/dotfiles         ││
# ││ Site    : https://www.roosta.sh                      ││
# ├┤ License : GNU General Public License v3              ├┤
# ┆└──────────────────────────────────────────────────────┘┆
# ┆ Docs: https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/

listener {
  timeout = 900                          # 5.5min
  on-timeout = hyprctl dispatch dpms off # screen off when timeout has passed
  on-resume = hyprctl dispatch dpms on   # screen on when activity is detected after timeout has fired.
}
