import QtQuick

QtObject {
  readonly property color black: "#121110"
  readonly property color red: "#EF2F27"
  readonly property color green: "#519F50"
  readonly property color yellow: "#FBB829"
  readonly property color blue: "#2C78BF"
  readonly property color magenta: "#E02C6D"
  readonly property color cyan: "#0AAEB3"
  readonly property color white: "#C5B088"
  readonly property color brightBlack: "#917E6B"
  readonly property color brightRed: "#F75341"
  readonly property color brightGreen: "#98BC37"
  readonly property color brightYellow: "#FED06E"
  readonly property color brightBlue: "#68A8E4"
  readonly property color brightMagenta: "#FF5C8F"
  readonly property color brightCyan: "#2BE4D0"
  readonly property color brightWhite: "#FCE8C3"
  readonly property color orange: "#FF5F00"
  readonly property color brightOrange: "#FF8700"
  readonly property color teal: "#008080"
  readonly property color gray1: "#1C1B19"
  readonly property color gray2: "#262522"
  readonly property color gray3: "#312F2C"
  readonly property color gray4: "#3B3935"
  readonly property color gray5: "#45433E"
  readonly property color gray6: "#504D47"
}
